apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: demo-app.info
      http:
        paths:
          - path: /api
            backend:
              serviceName: backend
              servicePort: 8080
          - path: /
            backend:
              serviceName: frontend
              servicePort: 8080
